export const COINS = [
  { symbol: 'BTC',  name: 'Bitcoin',  color: '#F7931A' },
  { symbol: 'ETH',  name: 'Ethereum', color: '#627EEA' },
  { symbol: 'SOL',  name: 'Solana',   color: '#9945FF' },
  { symbol: 'XRP',  name: 'XRP',      color: '#00AAE4' },
  { symbol: 'DOGE', name: 'Dogecoin', color: '#C3A634' },
];

// 50-coin universe scanned for run setups
export const SCAN_UNIVERSE = [
  { symbol: 'BTC',   name: 'Bitcoin',         color: '#F7931A' },
  { symbol: 'ETH',   name: 'Ethereum',        color: '#627EEA' },
  { symbol: 'SOL',   name: 'Solana',          color: '#9945FF' },
  { symbol: 'XRP',   name: 'XRP',             color: '#00AAE4' },
  { symbol: 'DOGE',  name: 'Dogecoin',        color: '#C3A634' },
  { symbol: 'BNB',   name: 'BNB',             color: '#F3BA2F' },
  { symbol: 'ADA',   name: 'Cardano',         color: '#0D9DE0' },
  { symbol: 'AVAX',  name: 'Avalanche',       color: '#E84142' },
  { symbol: 'MATIC', name: 'Polygon',         color: '#8247E5' },
  { symbol: 'DOT',   name: 'Polkadot',        color: '#E6007A' },
  { symbol: 'LINK',  name: 'Chainlink',       color: '#375BD2' },
  { symbol: 'LTC',   name: 'Litecoin',        color: '#A0A0A0' },
  { symbol: 'BCH',   name: 'Bitcoin Cash',    color: '#8DC351' },
  { symbol: 'ATOM',  name: 'Cosmos',          color: '#6F7390' },
  { symbol: 'NEAR',  name: 'NEAR Protocol',   color: '#00C08B' },
  { symbol: 'UNI',   name: 'Uniswap',         color: '#FF007A' },
  { symbol: 'AAVE',  name: 'Aave',            color: '#B6509E' },
  { symbol: 'FIL',   name: 'Filecoin',        color: '#42C1CA' },
  { symbol: 'GRT',   name: 'The Graph',       color: '#6F4CFF' },
  { symbol: 'SAND',  name: 'The Sandbox',     color: '#04ADEF' },
  { symbol: 'MANA',  name: 'Decentraland',    color: '#FF2D55' },
  { symbol: 'AXS',   name: 'Axie Infinity',   color: '#0055D5' },
  { symbol: 'VET',   name: 'VeChain',         color: '#15BDFF' },
  { symbol: 'XLM',   name: 'Stellar',         color: '#9B59B6' },
  { symbol: 'TRX',   name: 'TRON',            color: '#FF060A' },
  { symbol: 'INJ',   name: 'Injective',       color: '#00BFFF' },
  { symbol: 'APT',   name: 'Aptos',           color: '#2D8CFF' },
  { symbol: 'ARB',   name: 'Arbitrum',        color: '#28A0F0' },
  { symbol: 'OP',    name: 'Optimism',        color: '#FF0420' },
  { symbol: 'STX',   name: 'Stacks',          color: '#5546FF' },
  { symbol: 'ALGO',  name: 'Algorand',        color: '#00BB99' },
  { symbol: 'HBAR',  name: 'Hedera',          color: '#00B9B9' },
  { symbol: 'ICP',   name: 'Internet Computer', color: '#29ABE2' },
  { symbol: 'FTM',   name: 'Fantom',          color: '#1969FF' },
  { symbol: 'THETA', name: 'Theta',           color: '#2AB8E6' },
  { symbol: 'RUNE',  name: 'THORChain',       color: '#00CCAA' },
  { symbol: 'CRV',   name: 'Curve',           color: '#FF8C42' },
  { symbol: 'SNX',   name: 'Synthetix',       color: '#00D1FF' },
  { symbol: 'CHZ',   name: 'Chiliz',          color: '#CD0124' },
  { symbol: 'ENJ',   name: 'Enjin',           color: '#7B3FE4' },
  { symbol: 'FLOW',  name: 'Flow',            color: '#00EF8B' },
  { symbol: 'KAVA',  name: 'Kava',            color: '#FF564F' },
  { symbol: 'CAKE',  name: 'PancakeSwap',     color: '#FF9D00' },
  { symbol: 'MINA',  name: 'Mina',            color: '#E39844' },
  { symbol: 'IMX',   name: 'ImmutableX',      color: '#17B5CB' },
  { symbol: 'EGLD',  name: 'MultiversX',      color: '#1D60E0' },
  { symbol: 'ZIL',   name: 'Zilliqa',         color: '#29CCC4' },
  { symbol: 'CFX',   name: 'Conflux',         color: '#15C784' },
  { symbol: 'ONE',   name: 'Harmony',         color: '#00ADE8' },
  { symbol: 'ROSE',  name: 'Oasis',           color: '#0092F6' },
];

// Look up any coin by symbol — covers both watchlist and scanner universe
export function findCoin(symbol) {
  return SCAN_UNIVERSE.find(c => c.symbol === symbol) ?? null;
}
